structure(list(type = c("table", "index", "table", "index", "table", 
"index", "table", "index", "table", "index", "table", "index", 
"table", "index", "table", "index", "table", "index", "index", 
"index", "table", "index", "table", "index", "table", "table", 
"index", "table", "index", "table", "index", "index", "index", 
"table", "index", "index", "table", "index", "index", "table", 
"index", "table", "index", "index", "table", "index", "table", 
"index", "index", "table", "index", "table", "index", "table", 
"index", "table", "index", "table", "index", "table", "index", 
"table", "index", "table", "index", "table", "index", "table", 
"index", "table", "index", "table", "index", "table", "index", 
"table", "index", "table", "index", "table", "index", "table", 
"index", "table", "index", "table", "index", "table", "index", 
"table", "table", "table", "table", "table", "table", "index", 
"table", "index", "index", "table", "table", "table", "index", 
"table", "index", "index", "index", "table", "table", "index", 
"table", "index", "table", "table", "index", "table", "index", 
"table", "index", "table", "index", "table", "index", "table", 
"index", "table", "index", "table", "index", "index", "table", 
"index", "table", "index", "index", "table", "index", "table", 
"index", "index", "index", "table", "index", "index", "index", 
"table", "index", "table", "index", "table", "index", "index", 
"table", "index", "table", "index", "table", "index", "index", 
"table", "index", "index", "table", "index", "index", "table", 
"index", "table", "index", "table", "index"), name = c("Authors", 
"idx_a_AuthorId", "Papers", "idx_p_PaperId", "FieldsOfStudy", 
"idx_fos_FieldOfStudyId", "FieldOfStudyChildren", "idx_fosc_FieldOfStudyId", 
"PaperFieldsOfStudy", "idx_pfos_PaperIdFoS", "PaperAuthorAffiliations", 
"idx_paa_PaperIdAuthorIdAffiliationId", "PaperReferences", "idx_pr_PaperIdReferenceId", 
"Affiliations", "idx_a_AffiliationId", "FirstNames", "idx_fn_FirstName", 
"idx_p_Year", "idx_p_DocType", "FirstNamesGender", "idx_fng_FirstName", 
"AuthorNameSplits", "idx_ans_AuthorPosition", "sqlite_stat1", 
"UnclearNamesGender", "idx_ung_FirstName", "crosswalk_fields", 
"idx_cf_ParentChildField", "PaperMainFieldsOfStudy", "idx_pmf_PaperId", 
"idx_pmf_Field0", "idx_pmf_Field1", "PaperAuthorUnique", "idx_pau_PaperAuthorId", 
"idx_pau_AuthorId", "author_sample", "idx_as_AuthorId", "idx_as_FirstName", 
"author_fields", "idx_af_AuthorField", "AuthorAffiliation", "idx_aa_AuthorAffilYear", 
"idx_aa_Affil", "paper_citations", "idx_pc_PaperReferenceIdYear", 
"author_gender", "idx_ag_AuthorId", "idx_ag_NameUsed", "paper_outcomes", 
"idx_po_PaperId", "estimation_sample_history", "idx_es_PaperIdAuthorIdYearhistory", 
"estimation_sample_geology", "idx_es_PaperIdAuthorIdYeargeology", 
"estimation_sample_economics", "idx_es_PaperIdAuthorIdYeareconomics", 
"estimation_sample_geography", "idx_es_PaperIdAuthorIdYeargeography", 
"estimation_sample_philosophy", "idx_es_PaperIdAuthorIdYearphilosophy", 
"estimation_sample_sociology", "idx_es_PaperIdAuthorIdYearsociology", 
"estimation_sample_materials_science", "idx_es_PaperIdAuthorIdYearmaterials_science", 
"estimation_sample_mathematics", "idx_es_PaperIdAuthorIdYearmathematics", 
"estimation_sample_biology", "idx_es_PaperIdAuthorIdYearbiology", 
"estimation_sample_computer_science", "idx_es_PaperIdAuthorIdYearcomputer_science", 
"estimation_sample_political_science", "idx_es_PaperIdAuthorIdYearpolitical_science", 
"estimation_sample_engineering", "idx_es_PaperIdAuthorIdYearengineering", 
"estimation_sample_psychology", "idx_es_PaperIdAuthorIdYearpsychology", 
"estimation_sample_environmental_science", "idx_es_PaperIdAuthorIdYearenvironmental_science", 
"estimation_sample_business", "idx_es_PaperIdAuthorIdYearbusiness", 
"estimation_sample_physics", "idx_es_PaperIdAuthorIdYearphysics", 
"estimation_sample_medicine", "idx_es_PaperIdAuthorIdYearmedicine", 
"estimation_sample_art", "idx_es_PaperIdAuthorIdYearart", "estimation_sample_chemistry", 
"idx_es_PaperIdAuthorIdYearchemistry", "linked_ids", "linking_info", 
"cohort_career_decomp", "cohort_career", "author_performance", 
"author_selfcites", "idx_asc_AuthorIdYear", "author_coauthor", 
"idx_aco_AuthorIdCoAuthorId", "idx_pr_PaperReferenceId", "linked_ids_advisors", 
"linking_info_advisors", "affiliation_outcomes", "idx_affo_AffiliationId", 
"author_collab", "idx_acllb_AuthorCoAuthorYear", "idx_acllb_CoAuthorIdYear", 
"idx_acllb_AuthorIdYear", "linked_ids_grants", "linking_info_grants", 
"idx_paa_AuthorIdAffiliationId", "NSF_Appropriation", "ix_NSF_Appropriation_GrantID", 
"NSF_FieldsOfStudy", "NSF_FoaInformation", "ix_NSF_FoaInformation_GrantID", 
"NSF_Fund", "ix_NSF_Fund_GrantID", "NSF_Institution", "ix_NSF_Institution_GrantID", 
"NSF_Investigator", "ix_NSF_Investigator_GrantID", "NSF_MAIN", 
"ix_NSF_MAIN_GrantID", "NSF_Performance_Institution", "ix_NSF_Performance_Institution_GrantID", 
"NSF_ProgramElement", "ix_NSF_ProgramElement_GrantID", "NSF_ProgramReference", 
"ix_NSF_ProgramReference_GrantID", "idx_paa_AffiliationId", "cng_institutions", 
"idx_cngi_unitid", "links_to_cng", "idx_ltc_fromidunitid", "idx_ltc_unitid", 
"cng_distances", "idx_cngd_unitid", "pq_authors", "idx_pqaut_goid", 
"idx_pqaut_uni", "idx_pqaut_fname", "pq_advisors", "idx_pqadv_idpos", 
"idx_pqadv_fname", "idx_pqadv_relid", "pq_fields", "idx_pqfld_idpos", 
"pq_unis", "idx_pqu_id", "pq_fields_mag", "idx_pqfm_id", "idx_pqfm_fos", 
"pq_info_linking", "idx_pil_goid", "author_info_linking", "idx_ail_AuthorId", 
"author_field0", "idx_af0_authorfield", "idx_af0_field", "current_links", 
"idx_t_AuthorIdgoid", "idx_t_goid", "current_links_advisors", 
"idx_cla_AuthorIdrelid", "idx_cla_relid", "author_panel", "idx_ap_AuthorIdYear", 
"author_citations", "idx_ac_AuthorIdYear", "author_output", "idx_ao_AuthorIdYear"
), tbl_name = c("Authors", "Authors", "Papers", "Papers", "FieldsOfStudy", 
"FieldsOfStudy", "FieldOfStudyChildren", "FieldOfStudyChildren", 
"PaperFieldsOfStudy", "PaperFieldsOfStudy", "PaperAuthorAffiliations", 
"PaperAuthorAffiliations", "PaperReferences", "PaperReferences", 
"Affiliations", "Affiliations", "FirstNames", "FirstNames", "Papers", 
"Papers", "FirstNamesGender", "FirstNamesGender", "AuthorNameSplits", 
"AuthorNameSplits", "sqlite_stat1", "UnclearNamesGender", "UnclearNamesGender", 
"crosswalk_fields", "crosswalk_fields", "PaperMainFieldsOfStudy", 
"PaperMainFieldsOfStudy", "PaperMainFieldsOfStudy", "PaperMainFieldsOfStudy", 
"PaperAuthorUnique", "PaperAuthorUnique", "PaperAuthorUnique", 
"author_sample", "author_sample", "author_sample", "author_fields", 
"author_fields", "AuthorAffiliation", "AuthorAffiliation", "AuthorAffiliation", 
"paper_citations", "paper_citations", "author_gender", "author_gender", 
"author_gender", "paper_outcomes", "paper_outcomes", "estimation_sample_history", 
"estimation_sample_history", "estimation_sample_geology", "estimation_sample_geology", 
"estimation_sample_economics", "estimation_sample_economics", 
"estimation_sample_geography", "estimation_sample_geography", 
"estimation_sample_philosophy", "estimation_sample_philosophy", 
"estimation_sample_sociology", "estimation_sample_sociology", 
"estimation_sample_materials_science", "estimation_sample_materials_science", 
"estimation_sample_mathematics", "estimation_sample_mathematics", 
"estimation_sample_biology", "estimation_sample_biology", "estimation_sample_computer_science", 
"estimation_sample_computer_science", "estimation_sample_political_science", 
"estimation_sample_political_science", "estimation_sample_engineering", 
"estimation_sample_engineering", "estimation_sample_psychology", 
"estimation_sample_psychology", "estimation_sample_environmental_science", 
"estimation_sample_environmental_science", "estimation_sample_business", 
"estimation_sample_business", "estimation_sample_physics", "estimation_sample_physics", 
"estimation_sample_medicine", "estimation_sample_medicine", "estimation_sample_art", 
"estimation_sample_art", "estimation_sample_chemistry", "estimation_sample_chemistry", 
"linked_ids", "linking_info", "cohort_career_decomp", "cohort_career", 
"author_performance", "author_selfcites", "author_selfcites", 
"author_coauthor", "author_coauthor", "PaperReferences", "linked_ids_advisors", 
"linking_info_advisors", "affiliation_outcomes", "affiliation_outcomes", 
"author_collab", "author_collab", "author_collab", "author_collab", 
"linked_ids_grants", "linking_info_grants", "PaperAuthorAffiliations", 
"NSF_Appropriation", "NSF_Appropriation", "NSF_FieldsOfStudy", 
"NSF_FoaInformation", "NSF_FoaInformation", "NSF_Fund", "NSF_Fund", 
"NSF_Institution", "NSF_Institution", "NSF_Investigator", "NSF_Investigator", 
"NSF_MAIN", "NSF_MAIN", "NSF_Performance_Institution", "NSF_Performance_Institution", 
"NSF_ProgramElement", "NSF_ProgramElement", "NSF_ProgramReference", 
"NSF_ProgramReference", "PaperAuthorAffiliations", "cng_institutions", 
"cng_institutions", "links_to_cng", "links_to_cng", "links_to_cng", 
"cng_distances", "cng_distances", "pq_authors", "pq_authors", 
"pq_authors", "pq_authors", "pq_advisors", "pq_advisors", "pq_advisors", 
"pq_advisors", "pq_fields", "pq_fields", "pq_unis", "pq_unis", 
"pq_fields_mag", "pq_fields_mag", "pq_fields_mag", "pq_info_linking", 
"pq_info_linking", "author_info_linking", "author_info_linking", 
"author_field0", "author_field0", "author_field0", "current_links", 
"current_links", "current_links", "current_links_advisors", "current_links_advisors", 
"current_links_advisors", "author_panel", "author_panel", "author_citations", 
"author_citations", "author_output", "author_output"), sql = c("CREATE TABLE Authors(\n                AuthorId INTEGER,\n                ImportanceRank INTEGER, \n                NormalizedName TEXT,\n                DisplayName TEXT,\n                LastKnownAffiliationId INTEGER,\n                PaperCount INTEGER,\n                PaperFamilyCount INTEGER,\n                CitationCount INTEGER,\n                CreatedDate TEXT\n                )", 
"CREATE UNIQUE INDEX idx_a_AuthorId \n                ON Authors (AuthorId ASC)\n            ", 
"CREATE TABLE Papers(\n                PaperId INTEGER,\n                ImportanceRank INTEGER, \n                Doi TEXT,\n                DocType TEXT,\n                PaperTitle TEXT,\n                OriginalTitle TEXT,\n                BookTitle TEXT,\n                Year INTEGER,\n                Date TEXT,\n                OnlineDate TEXT,\n                Publisher TEXT,\n                JournalId INTEGER,\n                ConferenceSeriesId INTEGER,\n                ConferenceInstanceId INTEGER,\n                Volume TEXT,\n                Issue TEXT,\n                FirstPage TEXT,\n                LastPage TEXT,\n                ReferenceCount INTEGER,\n                CitationCount INTEGER,\n                EstimatedCitation INTEGER,\n                OriginalVenue INTEGER,\n                FamilyId INTEGER,\n                FamilyRank INTEGER,\n                DocSubTypes TEXT,\n                CreatedDate TEXT\n                )", 
"CREATE UNIQUE INDEX idx_p_PaperId\n                ON Papers (PaperId ASC)\n            ", 
"CREATE TABLE FieldsOfStudy(\n                FieldOfStudyId INTEGER,\n                ImportanceRank INTEGER,\n                NormalizedName TEXT,\n                DisplayName TEXT,\n                MainType TEXT, \n                Level INTEGER,\n                PaperCount INTEGER,\n                PaperFamilyCount INTEGER,\n                CitationCount INTEGER,\n                CreatedDate TEXT\n                )", 
"CREATE UNIQUE INDEX idx_fos_FieldOfStudyId\n                ON FieldsOfStudy (FieldOfStudyId ASC)\n            ", 
"CREATE TABLE FieldOfStudyChildren(\n                FieldOfStudyId INTEGER,\n                ChildFieldOfStudyId INTEGER\n                )", 
"CREATE INDEX idx_fosc_FieldOfStudyId\n                ON FieldOfStudyChildren (FieldOfStudyId ASC)\n            ", 
"CREATE TABLE PaperFieldsOfStudy(\n                PaperId INTEGER,\n                FieldOfStudyId INTEGER,\n                Score NUMERIC\n                )", 
"CREATE UNIQUE INDEX idx_pfos_PaperIdFoS\n                ON PaperFieldsOfStudy (PaperId ASC, FieldOfStudyId ASC)\n            ", 
"CREATE TABLE PaperAuthorAffiliations(\n                PaperId INTEGER,\n                AuthorId INTEGER,\n                AffiliationId INTEGER,\n                AuthorSequenceNumber INTEGER,\n                OriginalAuthor TEXT,\n                OriginalAffiliation TEXT\n                )", 
"CREATE INDEX idx_paa_PaperIdAuthorIdAffiliationId\n                ON PaperAuthorAffiliations (PaperId ASC, AuthorId ASC, AffiliationId ASC)\n            ", 
"CREATE TABLE PaperReferences(\n                PaperId INTEGER,\n                PaperReferenceId INTEGER\n                )", 
"CREATE UNIQUE INDEX idx_pr_PaperIdReferenceId\n                ON PaperReferences (PaperId ASC, PaperReferenceId ASC)\n            ", 
"CREATE TABLE Affiliations(\n                AffiliationId INTEGER,\n                ImportanceRank INTEGER,\n                NormalizedName TEXT,\n                DisplayName TEXT,\n                GridId TEXT,\n                OfficialPage TEXT,\n                WikiPage TEXT,\n                PaperCount INTEGER,\n                PaperFamilyCount INTEGER,\n                CitationCount INTEGER,\n                Iso3166Code TEXT,\n                Latitude NUMERIC,\n                Longitude NUMERIC,\n                CreatedDate TEXT\n                )", 
"CREATE INDEX idx_a_AffiliationId\n                ON Affiliations (AffiliationId ASC)\n            ", 
"CREATE TABLE FirstNames(FirstName,AuthorCount)", "CREATE INDEX idx_fn_FirstName ON FirstNames (FirstName)", 
"CREATE INDEX idx_p_Year ON Papers (Year ASC) ", "CREATE INDEX idx_p_DocType ON Papers (DocType) ", 
"CREATE TABLE FirstNamesGender(\n  FirstName TEXT,\n  PersonCount INT,\n  ProbabilityFemale\n)", 
"CREATE INDEX idx_fng_FirstName ON FirstNamesGender (FirstName ASC)", 
"CREATE TABLE AuthorNameSplits(\n                AuthorId TEXT,\n                Position INTEGER,\n                Name TEXT\n                )", 
"CREATE INDEX idx_ans_AuthorPosition ON AuthorNameSplits (AuthorId, Position)", 
"CREATE TABLE sqlite_stat1(tbl,idx,stat)", "CREATE TABLE UnclearNamesGender(\n  FirstName TEXT,\n  PersonCount INT,\n  ProbabilityFemale\n)", 
"CREATE INDEX idx_ung_FirstName ON UnclearNamesGender (FirstName ASC)", 
"CREATE TABLE crosswalk_fields(\n  ParentFieldOfStudyId INT,\n  ChildFieldOfStudyId INT,\n  PaperCount,\n  TotalScore,\n  ParentLevel INT,\n  ChildLevel INT\n)", 
"CREATE UNIQUE INDEX idx_cf_ParentChildField ON crosswalk_fields (ParentFieldOfStudyId, ChildFieldOfStudyId, ParentLevel, ChildLevel) ", 
"CREATE TABLE PaperMainFieldsOfStudy(\n  PaperId INT,\n  Field0 INT,\n  Field1 INT,\n  OriginalFieldId INT\n)", 
"CREATE UNIQUE INDEX idx_pmf_PaperId ON PaperMainFieldsOfStudy (PaperId ASC) ", 
"CREATE INDEX idx_pmf_Field0 ON PaperMainFieldsOfStudy (Field0 ASC) ", 
"CREATE INDEX idx_pmf_Field1 ON PaperMainFieldsOfStudy (Field1 ASC) ", 
"CREATE TABLE PaperAuthorUnique(PaperId INT,AuthorId INT)", "CREATE UNIQUE INDEX idx_pau_PaperAuthorId ON PaperAuthorUnique (PaperId ASC, AuthorId ASC)", 
"CREATE INDEX idx_pau_AuthorId ON PaperAuthorUnique (AuthorId)", 
"CREATE TABLE author_sample(\n  AuthorId INT,\n  YearLastPub,\n  YearFirstPub,\n  PaperCount,\n  FirstName\n)", 
"CREATE UNIQUE INDEX idx_as_AuthorId ON author_sample (AuthorId ASC) ", 
"CREATE INDEX idx_as_FirstName ON author_sample (FirstName ASC)", 
"CREATE TABLE author_fields(\n  AuthorId INT,\n  FieldOfStudyId INT,\n  FieldClass,\n  Score,\n  FieldOfStudyCount,\n  HHIAllFields,\n  SumScoreAllFields,\n  PaperCountAllFields\n)", 
"CREATE UNIQUE INDEX idx_af_AuthorField ON author_fields (AuthorId ASC, FieldClass, FieldOfStudyId)", 
"CREATE TABLE AuthorAffiliation(\n  AuthorId INT,\n  AffiliationId INT,\n  Year INT\n)", 
"CREATE UNIQUE INDEX idx_aa_AuthorAffilYear ON AuthorAffiliation (AuthorId ASC, AffiliationId ASC, Year)", 
"CREATE INDEX idx_aa_Affil ON AuthorAffiliation (AffiliationId ASC) ", 
"CREATE TABLE paper_citations(\n  PaperReferenceId INT,\n  Year INT,\n  ReferencingDocType TEXT,\n  CitationCount\n)", 
"CREATE INDEX idx_pc_PaperReferenceIdYear on paper_citations (PaperReferenceId ASC, Year)", 
"CREATE TABLE author_gender(\n  AuthorId INT,\n  NameUsed,\n  NamePositionUsed,\n  PersonCount INT,\n  ProbabilityFemale\n)", 
"CREATE UNIQUE INDEX idx_ag_AuthorId ON author_gender (AuthorId ASC)", 
"CREATE INDEX idx_ag_NameUsed ON author_gender (NameUsed)", "CREATE TABLE paper_outcomes(\n  PaperId INT,\n  CitationCount_y10,\n  CitationCount_y5,\n  AuthorCount\n)", 
"CREATE UNIQUE INDEX idx_po_PaperId on paper_outcomes (PaperId ASC)", 
"CREATE TABLE estimation_sample_history(\n  PaperId INT,\n  AuthorId INT,\n  DocType TEXT,\n  Year INT,\n  JournalId INT,\n  CitationCount INT,\n  CitationCount_y10,\n  CitationCount_y5,\n  AuthorCount,\n  FieldLvl1 INT\n)", 
"CREATE UNIQUE INDEX idx_es_PaperIdAuthorIdYearhistory on estimation_sample_history (PaperId ASC, AuthorId, Year)", 
"CREATE TABLE estimation_sample_geology(\n  PaperId INT,\n  AuthorId INT,\n  DocType TEXT,\n  Year INT,\n  JournalId INT,\n  CitationCount INT,\n  CitationCount_y10,\n  CitationCount_y5,\n  AuthorCount,\n  FieldLvl1 INT\n)", 
"CREATE UNIQUE INDEX idx_es_PaperIdAuthorIdYeargeology on estimation_sample_geology (PaperId ASC, AuthorId, Year)", 
"CREATE TABLE estimation_sample_economics(\n  PaperId INT,\n  AuthorId INT,\n  DocType TEXT,\n  Year INT,\n  JournalId INT,\n  CitationCount INT,\n  CitationCount_y10,\n  CitationCount_y5,\n  AuthorCount,\n  FieldLvl1 INT\n)", 
"CREATE UNIQUE INDEX idx_es_PaperIdAuthorIdYeareconomics on estimation_sample_economics (PaperId ASC, AuthorId, Year)", 
"CREATE TABLE estimation_sample_geography(\n  PaperId INT,\n  AuthorId INT,\n  DocType TEXT,\n  Year INT,\n  JournalId INT,\n  CitationCount INT,\n  CitationCount_y10,\n  CitationCount_y5,\n  AuthorCount,\n  FieldLvl1 INT\n)", 
"CREATE UNIQUE INDEX idx_es_PaperIdAuthorIdYeargeography on estimation_sample_geography (PaperId ASC, AuthorId, Year)", 
"CREATE TABLE estimation_sample_philosophy(\n  PaperId INT,\n  AuthorId INT,\n  DocType TEXT,\n  Year INT,\n  JournalId INT,\n  CitationCount INT,\n  CitationCount_y10,\n  CitationCount_y5,\n  AuthorCount,\n  FieldLvl1 INT\n)", 
"CREATE UNIQUE INDEX idx_es_PaperIdAuthorIdYearphilosophy on estimation_sample_philosophy (PaperId ASC, AuthorId, Year)", 
"CREATE TABLE estimation_sample_sociology(\n  PaperId INT,\n  AuthorId INT,\n  DocType TEXT,\n  Year INT,\n  JournalId INT,\n  CitationCount INT,\n  CitationCount_y10,\n  CitationCount_y5,\n  AuthorCount,\n  FieldLvl1 INT\n)", 
"CREATE UNIQUE INDEX idx_es_PaperIdAuthorIdYearsociology on estimation_sample_sociology (PaperId ASC, AuthorId, Year)", 
"CREATE TABLE estimation_sample_materials_science(\n  PaperId INT,\n  AuthorId INT,\n  DocType TEXT,\n  Year INT,\n  JournalId INT,\n  CitationCount INT,\n  CitationCount_y10,\n  CitationCount_y5,\n  AuthorCount,\n  FieldLvl1 INT\n)", 
"CREATE UNIQUE INDEX idx_es_PaperIdAuthorIdYearmaterials_science on estimation_sample_materials_science (PaperId ASC, AuthorId, Year)", 
"CREATE TABLE estimation_sample_mathematics(\n  PaperId INT,\n  AuthorId INT,\n  DocType TEXT,\n  Year INT,\n  JournalId INT,\n  CitationCount INT,\n  CitationCount_y10,\n  CitationCount_y5,\n  AuthorCount,\n  FieldLvl1 INT\n)", 
"CREATE UNIQUE INDEX idx_es_PaperIdAuthorIdYearmathematics on estimation_sample_mathematics (PaperId ASC, AuthorId, Year)", 
"CREATE TABLE estimation_sample_biology(\n  PaperId INT,\n  AuthorId INT,\n  DocType TEXT,\n  Year INT,\n  JournalId INT,\n  CitationCount INT,\n  CitationCount_y10,\n  CitationCount_y5,\n  AuthorCount,\n  FieldLvl1 INT\n)", 
"CREATE UNIQUE INDEX idx_es_PaperIdAuthorIdYearbiology on estimation_sample_biology (PaperId ASC, AuthorId, Year)", 
"CREATE TABLE estimation_sample_computer_science(\n  PaperId INT,\n  AuthorId INT,\n  DocType TEXT,\n  Year INT,\n  JournalId INT,\n  CitationCount INT,\n  CitationCount_y10,\n  CitationCount_y5,\n  AuthorCount,\n  FieldLvl1 INT\n)", 
"CREATE UNIQUE INDEX idx_es_PaperIdAuthorIdYearcomputer_science on estimation_sample_computer_science (PaperId ASC, AuthorId, Year)", 
"CREATE TABLE estimation_sample_political_science(\n  PaperId INT,\n  AuthorId INT,\n  DocType TEXT,\n  Year INT,\n  JournalId INT,\n  CitationCount INT,\n  CitationCount_y10,\n  CitationCount_y5,\n  AuthorCount,\n  FieldLvl1 INT\n)", 
"CREATE UNIQUE INDEX idx_es_PaperIdAuthorIdYearpolitical_science on estimation_sample_political_science (PaperId ASC, AuthorId, Year)", 
"CREATE TABLE estimation_sample_engineering(\n  PaperId INT,\n  AuthorId INT,\n  DocType TEXT,\n  Year INT,\n  JournalId INT,\n  CitationCount INT,\n  CitationCount_y10,\n  CitationCount_y5,\n  AuthorCount,\n  FieldLvl1 INT\n)", 
"CREATE UNIQUE INDEX idx_es_PaperIdAuthorIdYearengineering on estimation_sample_engineering (PaperId ASC, AuthorId, Year)", 
"CREATE TABLE estimation_sample_psychology(\n  PaperId INT,\n  AuthorId INT,\n  DocType TEXT,\n  Year INT,\n  JournalId INT,\n  CitationCount INT,\n  CitationCount_y10,\n  CitationCount_y5,\n  AuthorCount,\n  FieldLvl1 INT\n)", 
"CREATE UNIQUE INDEX idx_es_PaperIdAuthorIdYearpsychology on estimation_sample_psychology (PaperId ASC, AuthorId, Year)", 
"CREATE TABLE estimation_sample_environmental_science(\n  PaperId INT,\n  AuthorId INT,\n  DocType TEXT,\n  Year INT,\n  JournalId INT,\n  CitationCount INT,\n  CitationCount_y10,\n  CitationCount_y5,\n  AuthorCount,\n  FieldLvl1 INT\n)", 
"CREATE UNIQUE INDEX idx_es_PaperIdAuthorIdYearenvironmental_science on estimation_sample_environmental_science (PaperId ASC, AuthorId, Year)", 
"CREATE TABLE estimation_sample_business(\n  PaperId INT,\n  AuthorId INT,\n  DocType TEXT,\n  Year INT,\n  JournalId INT,\n  CitationCount INT,\n  CitationCount_y10,\n  CitationCount_y5,\n  AuthorCount,\n  FieldLvl1 INT\n)", 
"CREATE UNIQUE INDEX idx_es_PaperIdAuthorIdYearbusiness on estimation_sample_business (PaperId ASC, AuthorId, Year)", 
"CREATE TABLE estimation_sample_physics(\n  PaperId INT,\n  AuthorId INT,\n  DocType TEXT,\n  Year INT,\n  JournalId INT,\n  CitationCount INT,\n  CitationCount_y10,\n  CitationCount_y5,\n  AuthorCount,\n  FieldLvl1 INT\n)", 
"CREATE UNIQUE INDEX idx_es_PaperIdAuthorIdYearphysics on estimation_sample_physics (PaperId ASC, AuthorId, Year)", 
"CREATE TABLE estimation_sample_medicine(\n  PaperId INT,\n  AuthorId INT,\n  DocType TEXT,\n  Year INT,\n  JournalId INT,\n  CitationCount INT,\n  CitationCount_y10,\n  CitationCount_y5,\n  AuthorCount,\n  FieldLvl1 INT\n)", 
"CREATE UNIQUE INDEX idx_es_PaperIdAuthorIdYearmedicine on estimation_sample_medicine (PaperId ASC, AuthorId, Year)", 
"CREATE TABLE estimation_sample_art(\n  PaperId INT,\n  AuthorId INT,\n  DocType TEXT,\n  Year INT,\n  JournalId INT,\n  CitationCount INT,\n  CitationCount_y10,\n  CitationCount_y5,\n  AuthorCount,\n  FieldLvl1 INT\n)", 
"CREATE UNIQUE INDEX idx_es_PaperIdAuthorIdYearart on estimation_sample_art (PaperId ASC, AuthorId, Year)", 
"CREATE TABLE estimation_sample_chemistry(\n  PaperId INT,\n  AuthorId INT,\n  DocType TEXT,\n  Year INT,\n  JournalId INT,\n  CitationCount INT,\n  CitationCount_y10,\n  CitationCount_y5,\n  AuthorCount,\n  FieldLvl1 INT\n)", 
"CREATE UNIQUE INDEX idx_es_PaperIdAuthorIdYearchemistry on estimation_sample_chemistry (PaperId ASC, AuthorId, Year)", 
"CREATE TABLE linked_ids(\n        AuthorId INT\n        , goid INT \n        , link_score REAL\n        , iteration_id INT)", 
"CREATE TABLE linking_info(\n        iteration_id INT\n        , field TEXT\n        , recall REAL\n        , startyear INT\n        , endyear INT\n        , date TEXT\n        , testing INT\n        , n_match INT\n        , n_distinct INT\n        , train_name TEXT\n        , institution INT\n        , fieldofstudy_cat INT\n        , fieldofstudy_str INT\n        , keywords INT\n        , mergemode TEXT\n    )", 
"CREATE TABLE `cohort_career_decomp` (\n  `gender` TEXT,\n  `cohort` REAL,\n  `YearsExperience` REAL,\n  `CovQualQuant` REAL,\n  `CitationPerPaper` REAL,\n  `PaperCount` REAL,\n  `TotalForwardCitations` REAL,\n  `AuthorCount` INTEGER,\n  `FieldOfStudyId` INTEGER\n)", 
"CREATE TABLE `cohort_career` (\n  `cohort` TEXT,\n  `YearsExperience` INTEGER,\n  `gender` TEXT,\n  `TeamSize` REAL,\n  `AnyPaper` REAL,\n  `PaperCount_intensive` REAL,\n  `ForwardCitations_intensive` REAL,\n  `CitationCount` REAL,\n  `PaperCount` REAL,\n  `ForwardCitations` REAL,\n  `AuthorCount` INTEGER,\n  `ForwardCitationsPerNewPaper` REAL,\n  `ForwardCitationsPerNewPaper_intensive` REAL,\n  `AuthorCountStart` INTEGER,\n  `SurvivalRate` REAL,\n  `FieldOfStudyId` INTEGER\n)", 
"CREATE TABLE `author_performance` (\n  `AuthorId` INTEGER,\n  `CitationCount` INTEGER,\n  `PaperCount` INTEGER,\n  `CitationCount_start` REAL,\n  `PaperCount_start` REAL\n)", 
"CREATE TABLE author_selfcites(\n  AuthorId INT,\n  Year INT,\n  ReferencingYear INT,\n  CitationCount\n)", 
"CREATE UNIQUE INDEX idx_asc_AuthorIdYear on author_selfcites (AuthorId ASC, Year, ReferencingYear)", 
"CREATE TABLE author_coauthor(AuthorId INT,CoAuthorId INT)", 
"CREATE UNIQUE INDEX idx_aco_AuthorIdCoAuthorId on author_coauthor (AuthorId ASC, CoAuthorId ASC)", 
"CREATE INDEX idx_pr_PaperReferenceId ON PaperReferences (PaperReferenceId ASC)", 
"CREATE TABLE linked_ids_advisors(\n            relationship_id TEXT\n                        , AuthorId INT\n            , link_score REAL\n            , iteration_id INT)", 
"CREATE TABLE linking_info_advisors(\n        iteration_id INT\n        , field TEXT\n        , recall REAL\n        , startyear INT\n        , endyear INT\n        , date TEXT\n        , testing INT\n        , n_match INT\n        , n_distinct INT\n        , train_name TEXT\n        , institution INT\n        , fieldofstudy_cat INT\n        , fieldofstudy_str INT\n        , keywords INT\n        , mergemode TEXT\n    )", 
"CREATE TABLE affiliation_outcomes(\n  PublicationCount,\n  AffiliationId INT\n)", 
"CREATE UNIQUE INDEX idx_affo_AffiliationId ON affiliation_outcomes (AffiliationId ASC)", 
"CREATE TABLE author_collab (AuthorId INTEGER, CoAuthorId INTEGER, Year INTEGER)", 
"CREATE UNIQUE INDEX idx_acllb_AuthorCoAuthorYear ON author_collab (AuthorId ASC, CoAuthorId ASC, Year)", 
"CREATE INDEX idx_acllb_CoAuthorIdYear ON author_collab (CoAuthorId ASC, Year)", 
"CREATE INDEX idx_acllb_AuthorIdYear ON author_collab (AuthorId ASC, Year)", 
"CREATE TABLE linked_ids_grants(\n            GrantID TEXT\n                        , AuthorId INT\n            , link_score REAL\n            , iteration_id INT)", 
"CREATE TABLE linking_info_grants(\n        iteration_id INT\n        , field TEXT\n        , recall REAL\n        , startyear INT\n        , endyear INT\n        , date TEXT\n        , testing INT\n        , n_match INT\n        , n_distinct INT\n        , train_name TEXT\n        , institution INT\n        , fieldofstudy_cat INT\n        , fieldofstudy_str INT\n        , keywords INT\n        , mergemode TEXT\n    )", 
"CREATE INDEX idx_paa_AuthorIdAffiliationId ON PaperAuthorAffiliations (AuthorId ASC, AffiliationId ASC)", 
"CREATE TABLE \"NSF_Appropriation\" (\n\"GrantID\" TEXT,\n  \"Folder\" INTEGER,\n  \"Position\" INTEGER,\n  \"Code\" TEXT,\n  \"Name\" TEXT,\n  \"AppSymbID\" TEXT\n)", 
"CREATE INDEX \"ix_NSF_Appropriation_GrantID\"ON \"NSF_Appropriation\" (\"GrantID\")", 
"CREATE TABLE \"NSF_FieldsOfStudy\" (\n\"Organization_Directorate_Abbreviation\" TEXT,\n  \"Organization_Directorate_ShortName\" TEXT,\n  \"Organization_Division_Abbreviation\" TEXT,\n  \"Organization_Division_ShortName\" TEXT,\n  \"NormalizedName\" TEXT\n)", 
"CREATE TABLE \"NSF_FoaInformation\" (\n\"GrantID\" TEXT,\n  \"Folder\" INTEGER,\n  \"Position\" INTEGER,\n  \"Code\" TEXT,\n  \"Name\" TEXT\n)", 
"CREATE INDEX \"ix_NSF_FoaInformation_GrantID\"ON \"NSF_FoaInformation\" (\"GrantID\")", 
"CREATE TABLE \"NSF_Fund\" (\n\"GrantID\" TEXT,\n  \"Folder\" INTEGER,\n  \"Position\" INTEGER,\n  \"Code\" TEXT,\n  \"Name\" TEXT,\n  \"FundSymbID\" INTEGER\n)", 
"CREATE INDEX \"ix_NSF_Fund_GrantID\"ON \"NSF_Fund\" (\"GrantID\")", 
"CREATE TABLE \"NSF_Institution\" (\n\"GrantID\" TEXT,\n  \"Folder\" INTEGER,\n  \"Position\" INTEGER,\n  \"Name\" TEXT,\n  \"CityName\" TEXT,\n  \"ZipCode\" TEXT,\n  \"PhoneNumber\" TEXT,\n  \"StreetAddress\" TEXT,\n  \"CountryName\" TEXT,\n  \"StateName\" TEXT,\n  \"StateCode\" TEXT,\n  \"CONGRESSDISTRICT\" TEXT,\n  \"CongressDistrictOrg\" TEXT,\n  \"OrgUEINum\" TEXT,\n  \"OrgLGLBusName\" TEXT,\n  \"OrgPrntUEINum\" TEXT,\n  \"StreetAddress2\" TEXT,\n  \"OrgDUNSNum\" REAL,\n  \"OrgPrntDUNSNum\" REAL,\n  \"CountyName\" TEXT\n)", 
"CREATE INDEX \"ix_NSF_Institution_GrantID\"ON \"NSF_Institution\" (\"GrantID\")", 
"CREATE TABLE \"NSF_Investigator\" (\n\"GrantID\" TEXT,\n  \"Folder\" INTEGER,\n  \"Position\" INTEGER,\n  \"FirstName\" TEXT,\n  \"LastName\" TEXT,\n  \"PIFullName\" TEXT,\n  \"EmailAddress\" TEXT,\n  \"PIPhon\" TEXT,\n  \"NSFID\" TEXT,\n  \"StartDate\" TEXT,\n  \"RoleCode\" TEXT,\n  \"PIMidInit\" TEXT,\n  \"PISufxName\" TEXT,\n  \"EndDate\" TEXT,\n  \"EndDateEpoch\" REAL,\n  \"RecentPIFlag\" REAL,\n  \"ID\" TEXT,\n  \"StartDateEpoch\" TEXT,\n  \"StartYear\" TEXT,\n  \"EndYear\" TEXT,\n  \"StartYearEpoch\" TEXT\n)", 
"CREATE INDEX \"ix_NSF_Investigator_GrantID\"ON \"NSF_Investigator\" (\"GrantID\")", 
"CREATE TABLE \"NSF_MAIN\" (\n\"GrantID\" TEXT,\n  \"Folder\" INTEGER,\n  \"Position\" INTEGER,\n  \"Award_AwardTitle\" TEXT,\n  \"Award_AGENCY\" TEXT,\n  \"Award_AwardEffectiveDate\" TEXT,\n  \"Award_AwardExpirationDate\" TEXT,\n  \"Award_AwardTotalIntnAmount\" REAL,\n  \"Award_AwardAmount\" REAL,\n  \"Award_AbstractNarration\" TEXT,\n  \"Award_MinAmdLetterDate\" TEXT,\n  \"Award_MaxAmdLetterDate\" TEXT,\n  \"Award_TranType\" TEXT,\n  \"Award_CfdaNum\" TEXT,\n  \"Award_NSFParUseFlag\" REAL,\n  \"Award_FundAgcyCode\" REAL,\n  \"Award_AwdgAgcyCode\" REAL,\n  \"Award_AwardID\" INTEGER,\n  \"Award_FundOblg\" TEXT,\n  \"Award_ARRAAmount\" REAL,\n  \"Award_AwardEffectiveYear\" TEXT,\n  \"Award_AwardExpirationYear\" TEXT,\n  \"Award_MinAmdLetterYear\" TEXT,\n  \"Award_MaxAmdLetterYear\" TEXT,\n  \"AwardInstrument_Value\" TEXT,\n  \"Organization_Code\" REAL,\n  \"Organization_Directorate_Abbreviation\" TEXT,\n  \"Organization_Directorate_LongName\" TEXT,\n  \"Organization_Division_Abbreviation\" TEXT,\n  \"Organization_Division_LongName\" TEXT,\n  \"POR_DRECONTENT\" TEXT,\n  \"POR_PorCopyTxt\" TEXT,\n  \"ProgramOfficer_SignBlockName\" TEXT,\n  \"ProgramOfficer_PoEmai\" TEXT,\n  \"ProgramOfficer_PoPhon\" REAL,\n  \"Organization_Directorate_ShortName\" TEXT,\n  \"Organization_Division_ShortName\" TEXT\n)", 
"CREATE INDEX \"ix_NSF_MAIN_GrantID\"ON \"NSF_MAIN\" (\"GrantID\")", 
"CREATE TABLE \"NSF_Performance_Institution\" (\n\"GrantID\" TEXT,\n  \"Folder\" INTEGER,\n  \"Position\" INTEGER,\n  \"Name\" TEXT,\n  \"CityName\" TEXT,\n  \"StateCode\" TEXT,\n  \"ZipCode\" TEXT,\n  \"StreetAddress\" TEXT,\n  \"CountryCode\" TEXT,\n  \"CountryName\" TEXT,\n  \"StateName\" TEXT,\n  \"CountryFlag\" REAL,\n  \"CONGRESSDISTRICT\" TEXT,\n  \"CongressDistrictPerf\" TEXT,\n  \"CountyName\" TEXT\n)", 
"CREATE INDEX \"ix_NSF_Performance_Institution_GrantID\"ON \"NSF_Performance_Institution\" (\"GrantID\")", 
"CREATE TABLE \"NSF_ProgramElement\" (\n\"GrantID\" TEXT,\n  \"Folder\" INTEGER,\n  \"Position\" INTEGER,\n  \"Code\" TEXT,\n  \"Text\" TEXT\n)", 
"CREATE INDEX \"ix_NSF_ProgramElement_GrantID\"ON \"NSF_ProgramElement\" (\"GrantID\")", 
"CREATE TABLE \"NSF_ProgramReference\" (\n\"GrantID\" TEXT,\n  \"Folder\" INTEGER,\n  \"Position\" INTEGER,\n  \"Code\" TEXT,\n  \"Text\" TEXT\n)", 
"CREATE INDEX \"ix_NSF_ProgramReference_GrantID\"ON \"NSF_ProgramReference\" (\"GrantID\")", 
"CREATE INDEX idx_paa_AffiliationId ON PaperAuthorAffiliations (AffiliationId ASC)", 
"CREATE TABLE \"cng_institutions\" (\n\"unitid\" INTEGER,\n  \"normalizedname\" TEXT,\n  \"originalname\" TEXT,\n  \"city\" TEXT,\n  \"stabbr\" TEXT,\n  \"basic2021\" INTEGER,\n  \"latitude\" REAL,\n  \"longitude\" REAL\n)", 
"CREATE UNIQUE INDEX idx_cngi_unitid ON cng_institutions (unitid ASC)", 
"CREATE TABLE \"links_to_cng\" (\n\"from_id\" INTEGER,\n  \"unitid\" INTEGER,\n  \"link_score\" REAL,\n  \"link_flag\" TEXT,\n  \"from_dataset\" TEXT\n)", 
"CREATE INDEX idx_ltc_fromidunitid ON links_to_cng(from_id ASC, unitid ASC)", 
"CREATE INDEX idx_ltc_unitid ON links_to_cng(unitid ASC)", "CREATE TABLE \"cng_distances\" (\n\"unitid\" INTEGER,\n  \"unitid2\" INTEGER,\n  \"distance_km\" REAL\n)", 
"CREATE UNIQUE INDEX idx_cngd_unitid ON cng_distances (unitid ASC, unitid2 ASC)", 
"CREATE TABLE pq_authors( goid INTEGER\n            , fullname TEXT\n            , firstname TEXT\n            , degree_year INTEGER\n            , degree_level TEXT\n            , university_id INTEGER\n            , department TEXT\n            , originaltitle TEXT\n            , thesistitle TEXT )", 
"CREATE UNIQUE INDEX idx_pqaut_goid ON pq_authors (goid ASC)", 
"CREATE INDEX idx_pqaut_uni ON pq_authors (university_id ASC)", 
"CREATE INDEX idx_pqaut_fname ON pq_authors (firstname ASC)", 
"CREATE TABLE pq_advisors( goid INTEGER\n            , position INTEGER\n            , lastname TEXT\n            , firstname TEXT\n            , relationship_id TEXT )", 
"CREATE INDEX idx_pqadv_idpos ON pq_advisors (goid ASC)", "CREATE INDEX idx_pqadv_fname ON pq_advisors (firstname ASC)", 
"CREATE UNIQUE INDEX idx_pqadv_relid ON pq_advisors(relationship_id)", 
"CREATE TABLE pq_fields( goid INTEGER\n            , position INTEGER\n            , fieldname TEXT\n            , fieldcode INTEGER )", 
"CREATE INDEX idx_pqfld_idpos ON pq_fields (goid ASC)", "CREATE TABLE pq_unis( university_id INTEGER\n            , originalname TEXT\n            , normalizedname TEXT\n            , location TEXT\n            , us_stabbr TEXT\n             )", 
"CREATE UNIQUE INDEX idx_pqu_id ON pq_unis (university_id ASC)", 
"CREATE TABLE pq_fields_mag (\n        goid INT\n        , position INT\n        , fieldname TEXT\n        , mag_field0 INT\n        , flag TEXT)", 
"CREATE UNIQUE INDEX idx_pqfm_id on pq_fields_mag (goid ASC, mag_field0 ASC)", 
"CREATE INDEX idx_pqfm_fos on pq_fields_mag (mag_field0 ASC)", 
"CREATE TABLE pq_info_linking(\n  goid INT,\n  fields,\n  advisors\n)", 
"CREATE UNIQUE INDEX idx_pil_goid ON pq_info_linking (goid ASC)", 
"CREATE TABLE author_info_linking(\n  AuthorId INT,\n  keywords,\n  institutions,\n  coauthors,\n  main_institutions_career,\n  main_us_institutions_career,\n  main_us_institutions_year,\n  all_us_institutions_year,\n  year_papertitle\n)", 
"CREATE UNIQUE INDEX idx_ail_AuthorId ON author_info_linking (AuthorId ASC)", 
"CREATE TABLE author_field0(\n  AuthorId INT,\n  FieldOfStudyId_lvl0 INT,\n  Degree\n)", 
"CREATE UNIQUE INDEX idx_af0_authorfield ON author_field0 (AuthorId ASC, FieldOfStudyId_lvl0 ASC) ", 
"CREATE INDEX idx_af0_field ON author_field0 (FieldOfStudyId_lvl0 ASC) ", 
"CREATE TABLE current_links(\n  AuthorId INT,\n  goid INT,\n  link_score REAL,\n  iteration_id INT\n)", 
"CREATE UNIQUE INDEX idx_t_AuthorIdgoid ON current_links (AuthorId ASC, goid ASC)", 
"CREATE UNIQUE INDEX idx_t_goid ON current_links (goid ASC)", 
"CREATE TABLE current_links_advisors(\n  AuthorId INT,\n  relationship_id TEXT,\n  link_score REAL,\n  iteration_id INT\n)", 
"CREATE UNIQUE INDEX idx_cla_AuthorIdrelid ON current_links_advisors (AuthorId ASC, relationship_id ASC)", 
"CREATE UNIQUE INDEX idx_cla_relid ON current_links_advisors (relationship_id ASC)", 
"CREATE TABLE author_panel(AuthorId INT,Year INT)", "CREATE UNIQUE INDEX idx_ap_AuthorIdYear on author_panel (AuthorId ASC, Year)", 
"CREATE TABLE author_citations(\n  AuthorId INT,\n  Year INT,\n  CitationCount\n)", 
"CREATE UNIQUE INDEX idx_ac_AuthorIdYear on author_citations (AuthorId ASC, Year)", 
"CREATE TABLE author_output(\n  AuthorId INT,\n  Year INT,\n  PaperCount,\n  TotalAuthorCount,\n  TotalForwardCitations\n)", 
"CREATE UNIQUE INDEX idx_ao_AuthorIdYear on author_output (AuthorId ASC, Year)"
)), class = "data.frame", row.names = c(NA, -171L))
